### ISSUE TITLE
Add documentation on how to start contributing

### ISSUE THREAD

**Issue by finalspy** [elcharitas/chakra-ui-svelte#1]
Could you please add a short section in the Readme on :

- how we could start contributing 
- and setup this project properly as a developer ? 

This could help onboard new commiters to help you in implementing new chakraui components :) 
Thanks for this projects looks very promising 👍🏻

**Comment by elcharitas** [comment]
@finalspy this is an excellent suggestion. I intend to revamp the project a bit. Then I'd add the necessary guides as well.

I'll keep this Issue open and update it once this is done
